### ISSUE TITLE
gaussianMatrices for gaussianRing Digraph error

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#101]
`D=digraph{{1,6},{4,7}}`
`Stmts = {{{1,6},{4},{7}}, {{6},{7},{}}}`
`gaussianMatrices (gaussianRing D, Stmts)`
gives error stdio:96:1:(3): error: key not found in hash table

(it works with gaussianMatrices (gaussianRing mixedGraph D, Stmts) and for Bigraphs and Graphs taken both separately and as mixedGraph(B), mixedGraph(G))

Related to #98, #99, #100

**Comment by olgakuznetsova** [comment]
similar bug in conditionalIndependenceIdeal (gaussianRing D, Stmts). probably will be fixed by #100

**Comment by roserhp** [comment]
Solved
