### ISSUE TITLE
Unclear what $S$ is in the documentation

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#102]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/ffb2fb754e94c6083883b2c9a7c2703e6cb61b84/AlgebraicStatistics/GraphicalModels.m2#L2577

**Comment by roserhp** [comment]
I think $S$ here refers to symbol s, the one which represents the variables s, i.e. the ones we used for covariance matrices. But let's see what Luis and Carlos say.

**Comment by luisgarciapuente** [comment]
Good catch. It should be Stmts instead of S
