### ISSUE TITLE
gaussianVanishingIdeal confusing documentation

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#105]
1. In the code, there is a commented out comment that says
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/ffb2fb754e94c6083883b2c9a7c2703e6cb61b84/AlgebraicStatistics/MLE/GraphicalModels.m2#L995
but it is not mentioned in the user documentation

2. Input documentation should say that only MixedGraphs without undirected edges are accepted

3. If I run 
` gaussianVanishingIdeal gaussianRing 3`
I do not get any of the standard pre-defined error and instead get
stdio:126:1:(3): error: key not found in hash table

**Comment by roserhp** [comment]
3. Error message is now the right one.
2. Olga is absolutely right. It can also take as input gaussianRings from Bigraphs and Digraphs (basically because they are build as gaussianRings mixedGraphs).
