### ISSUE TITLE
gaussianVanishingIdeal - inconsistent error messages

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#111]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1e338517847fc409648b6c407a1921139397e4a0/AlgebraicStatistics/MLE/GraphicalModels.m2#L965-L1014

In the beginning, it says
`if not R.?graph then error "expected a ring created with gaussianRing";`
but this is actually checking whether it is a gaussianRing of some graph, not just a gaussianRing. So, if you run
`gaussianVanishingIdeal gaussianRing 3`
you don't reach the line 
`else error " gaussianVanishingIdeal expected a ring created with gaussianRing of a Graph or Digraph or MixedGraph"   `

**Comment by roserhp** [comment]
You are right. It's fixed now in AlgebraicStatistics branch.
