### ISSUE TITLE
bugs in discreteVanishingIdeal

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#112]
1. The first example from the documentation https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.12/share/doc/Macaulay2/GraphicalModels/html/_discrete__Vanishing__Ideal.html does not run

`G = digraph {{1,{}}, {2,{}}}`
`R = markovRing (2,2)`
`discreteVanishingIdeal (R,G)`
gives error
stdio:4:1:(3): error: no method found for applying promote to:
     argument 1 :  0 (of class QQ[p   , p   , p   , p   ])
                                   1,1   1,2   2,1   2,2
     argument 2 :  QQ[p   , p   , p   , p   ]
                       1,1   1,2   2,1   2,2

2. also, if I substitute a wrong type of ring, say
`G=graph{{1,2},{1,3},{2,3}}`
`discreteVanishingIdeal (R,G)`
it doesn't say that the graph is incompatible. Instead, it gives 
stdio:8:1:(3): error: Number of vertices of graph does not match size of ring

3. and it doesn't seem that the function checks anywhere that the graph is actually a Digraph.

**Comment by roserhp** [comment]
1. is fixed by #117. Check and subsequent error message added to fix 2. and 3.
