### ISSUE TITLE
errors in marginMap and inverseMarginMap

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#116]
1. When I run
d=(2,3,4,5);
R = markovRing d
marginMap(1,R)
I get the error
stdio:19:1:(3): error: no method found for applying promote to:
     argument 1 :  p        - p     . (of class QQ[p       , p       , p     .)
                    1,1,1,1    2,1,1.               1,1,1,1   1,1,1,2   1,1,1.
     argument 2 :  R

2. The documentation should probably be hyperlinked to markovRing https://faculty.math.illinois.edu/Macaulay2/doc/Macaulay2-1.16/share/doc/Macaulay2/GraphicalModels/html/_margin__Map.html

3. Same for inverseMarginMap

**Comment by roserhp** [comment]
Should be fixed by the solution of #117 because it's the same king of error.

**Comment by roserhp** [comment]
1. and 3. fixed by the solution of #117. I don't understand what 2. exactly means.
