### ISSUE TITLE
hiddenMap doesn't run

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#117]
If I run the example from the documentation
hiddenMap(1,markovRing(2,3,2))

I get error
stdio:2:1:(3): error: no method found for applying promote to:
     argument 1 :  p      + p      (of class QQ[p     , p     , p     , p .)
                    1,1,1    2,1,1               1,1,1   1,1,2   1,2,1   1.
     argument 2 :  QQ[p     , p     , p     , p     , p     , p     , p     , .
                       1,1,1   1,1,2   1,2,1   1,2,2   1,3,1   1,3,2   2,1,1  .
(tried restarting M2)

**Comment by roserhp** [comment]
Something must be different between the main branch (AlgebraicStatistics) and mine, because mine works fine.

**Comment by olgakuznetsova** [comment]
:( you can create a pull request to compare the two branches, just don't need to merge.

**Comment by roserhp** [comment]
I've found the origin of the problem. In the main branch, the elements of R.markovVariables are not considered elements in the ring R but as an element of anoter ring which is exactly the same if you look at its description. Therefore this is a problem in the creation of the markovRing itself. There are some changes in the function markovRing when I compare the main branch to mine but basically it boils down to line 505:

MarkovRing = new Type of PolynomialRing;

Is this something you did Olga? If I go back to the MarkovRing code I had in my branch it works fine. Is there any reason why we need this new changes?

**Comment by olgakuznetsova** [comment]
Gosh, I though I had deleted all of the instances of new Type of PolynomialRing. That's definitely my mistake, sorry about that.

**Comment by roserhp** [comment]
No worries. I'll change that in the next push at some point before today's meeting.

**Comment by roserhp** [comment]
Fixed in AlgebraicStatistics branch.
