### ISSUE TITLE
topologicalSort: convert second argument to optional input?

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#130]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/6238856191537b145dbc28c5d969f06de86396d9/AlgebraicStatistics/MLE/StatGraphs.m2#L51-L58

Is there a reason why the second argument String is defined this way and not as an optional input?

**Comment by olgakuznetsova** [comment]
@harshitmotwani2015 shall we close this as well?

**Comment by harshitmotwani2015** [comment]
Yes, I am closing it now.
