### ISSUE TITLE
Inconsistency between topSort and topologicalSort

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#132]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/6238856191537b145dbc28c5d969f06de86396d9/AlgebraicStatistics/MLE/StatGraphs.m2#L80-L89

Shouldn't topSort also allow input of the form (Digraph, String) as topologicalSort? Or rather, should it also have an optional argument? (see issue#130)

**Comment by harshitmotwani2015** [comment]
@olgakuznetsova  We have not removed topologicalSort from Graphs yet. We also have topologicalSort in StatGraphs (repetition of code in both packages).

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/d609ee6f2338e16a87581bf38dc715c3db756407/AlgebraicStatistics/MLE/Graphs.m2#L1131

**Comment by olgakuznetsova** [comment]
Good catch! I've just checked and topologicalSort does not appear anywhere outside Graphs in the M2 codebase, so I guess it's pretty safe to remove it but we will unfortunately need to redo issue #47. Also, topologicalSort is mentioned in the documentation of breadthFirstSearch and depthFirstSearch, so let's delete the references o/w it can cause problems during the installation of Graphs.

**Comment by olgakuznetsova** [comment]
On the second thought: would it make sense to keep topologicalSort and topSort in Graphs? They take in Digraphs and topological sorting is not an intrinsically statistical operation, so it feels more natural to leave them there.
We just need to update the documentation and convert that String input into an optional input.

**Comment by harshitmotwani2015** [comment]
I agree that its better to keep topSort in Graphs? 
I have removed the inconsistency between topSort and topologicalSort. However, I have not added any optional method instead I have added a method for topSort to take input as strings. I think it disturbs the code less compare to adding options.

**Comment by olgakuznetsova** [comment]
When you move the two functions back to Graphs, could you also add these two tests?
--------------------------------------------
-- Topological sorting functions
--------------------------------------------

--------------------------------------------
-- Tests for  topologicalSort
--------------------------------------------
--17
TEST /// 

	   D = digraph{{2,1},{3,1}}
	   assert(topologicalSort D==={2,3,1})
   ///

--------------------------------------------
-- Tests for topSort
--------------------------------------------
--18
TEST /// 
    
	   D = digraph{{2,1},{3,1}}
	   assert(topSort D ===  new SortedDigraph from {map => new HashTable from {1 => 3, 2 => 1, 3
      => 2}, newDigraph => digraph ({1, 2, 3}, {{1, 3}, {2, 3}}), digraph =>
      digraph ({2, 1, 3}, {{2, 1}, {3, 1}})})
   ///

**Comment by olgakuznetsova** [comment]
@harshitmotwani2015 shall we close this?

**Comment by harshitmotwani2015** [comment]
Documentation and tests are still remaining for these two functions.
