### ISSUE TITLE
solverMLE

### ISSUE THREAD

**Issue by roserhp** [Macaulay2/Workshop-2020-Warwick#142]
- add check of singular data with warning
- add Carlos example to documentation examples and/or tests in GraphicalModelsMLE
- explain the options in solverMLE better in the documentation (default and optional)
- explain better the output of solverMLE in the documentation

**Comment by roserhp** [comment]
We should have an optional output which is the ML degree of the model. And even maybe some counter that says how many of the critical points were real and how many were PD. These can be very relevant for further research into these models. But it's not urgent we can take care of the other issues first.

**Comment by olgakuznetsova** [comment]
So maybe add the ML degree as a separate procedure and as a default in solverMLE as you suggested?

**Comment by roserhp** [comment]
So far in AlgebraicStatisticsRoser:
- warning message added for sampleCovarianceMatrix singular. Is that exactly what we wanted?
- new Carlos' examples added
- documentation improved
- ML-degree added as output (also a separate MLdegree function has been created)

Questions:
- Is documentation for solverMLE is ok and understandable? 
- What are exactly the data checks/warnings that we want? Only singularity of sampleCovarianceMatrix?
- Do we want counter that says how many of the critical points were real and how many were PD in this release?

**Comment by roserhp** [comment]
Things done according to yesterday's meeting:
1. Warning removed
2. Default set to covariance
4. No
5. No
6. Solved
7. Not for this release
