### ISSUE TITLE
errors while installing statGraphs

### ISSUE THREAD

**Issue by harshitmotwani2015** [Macaulay2/Workshop-2020-Warwick#146]
I got some errors in the examples 
error: 15 error(s) occurred running examples for package StatGraphs

These are documentations and examples related

**Comment by olgakuznetsova** [comment]
Could you copy the lines that say which examples didn’t run?

**Comment by roserhp** [comment]
I can install statgraphs without any problems... have you first uninstalled and installed Graphs?

**Comment by roserhp** [comment]
Sorry, I see that there are new pushes to the AlgebraicStatistics branch... I haven't tried to install StatGraphs since Thursday-Friday

**Comment by olgakuznetsova** [comment]
I just deleted and installed the StatGraphs package that's been on my branch and it seems to install without problems. Let me try with the latest from this branch

**Comment by olgakuznetsova** [comment]
also installs from the main branch. Could you try to pull the branch again and try re-installing again?
If you get errors again, please share the exact examples that cause problems.

**Comment by roserhp** [comment]
Yes, it worked for me as well for the latest version of the main branch, with no errors. Only warnings related to the documentation.

**Comment by harshitmotwani2015** [comment]
Now it's installing fine other than some warnings related to documentation. I think I had not uninstalled Graphs and installed it again before proceeding earlier. Thanks for the help.
