### ISSUE TITLE
conversion of matrix of sample data to list. 

### ISSUE THREAD

**Issue by harshitmotwani2015** [Macaulay2/Workshop-2020-Warwick#148]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/370ecd888ba2f127c0c6bbb27dac3480863f135a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L412

This converts a matrix of sample data to list where elements of the list are rows of the matrix

@olgakuznetsova 
Should this code be 
X = for i to n-1 list flatten entries U^{i}; 
(it will create list of lists (containing same data) instead of list of rows of matrix

**Comment by olgakuznetsova** [comment]
actually, our default type of lists is a list of matrices. However, @roserhp has just proposed to improve the syntaxes and drop the list of matrices thingie. So let's not touch this for now

**Comment by roserhp** [comment]
I'm reviewing the documentation of GraphicalModelsMLE and I find some inputs quite messy... So I'm trying to get rid of lists of matrices, which implies changing a bit some functions. If it works well in my branch, I'll let you know so that you can check it before the merge with the main one.

**Comment by roserhp** [comment]
I changed quite a lot of things in my branch... The idea is that now matrix input is the base input and lists are converted to matrices just by 
considering matrix(list). Here is the example for scoreEquations.

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1de9f08f04cc957a2c995ed54d235425e61b335a/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L259
