### ISSUE TITLE
Add vertex sorting in partitionLMG?

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#155]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/efa4e5df2c544d671f85c2ee144b26a254c12491/AlgebraicStatistics/MLE/StatGraphs.m2#L292

Should we also sort the final lists of vertices before giving the output?
Otherwise, this example looks a bit funny:
	   U = graph{{1,2},{2,3},{1,3}}
	   D = digraph{{1,4},{3,7},{8,9}}
	   B = bigraph{{4,5},{5,6},{7,9}}
	   G = mixedGraph(U,D,B)
	   partitionLMG G

**Comment by olgakuznetsova** [comment]
@roserhp  I am working on this package now, so if you are ok, I'll make the fix right away.

**Comment by roserhp** [comment]
sure, go ahead!
