### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by roserhp** [Macaulay2/Workshop-2020-Warwick#164]
Packages that have some kind of predetermined bibliography ( NumericalAlgebraicGeometry, Binomials...) have a different "template" for the documentation and I've tried a bit but I can't do the same thing.

I don't understand why there's no clear uniform way of writing documentation but I already wasted a lot of time on this...
From my side, I would just write references as in GraphicalModels.

Everyone agrees or someone wants to take over and fix this?

**Comment by olgakuznetsova** [comment]
Let's do like in GraphicalModels and fix it if someone complains (and tells us how to fix it)
