### ISSUE TITLE
gaussianRing mixedGraph: which mixed graphs are allowed? 

### ISSUE THREAD

**Issue by roserhp** [Macaulay2/Workshop-2020-Warwick#166]
Whenever a **mixedGraph** has **both** undirected and some other kind of edges (directed and/or bidirected), gaussianRing mixedGraph calls function **partitionLMG** in StatGraphs:

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/576babef07c2a1bd1a6c474195280d84ac3031e2/AlgebraicStatistics/MLE/StatGraphs.m2#L264

**partitionLMG** is designed so that the vertices of $G$ are partitioned into $U\cup W$ such that
    
     - if $i-j$ in $G$ then $i,j\in U$
    
    - if $i\leftarrow \rightarrow j$ in $G$ then $i,j\in W$ 
    
    -  there is no directed edge $i\to j$ in $G$ such that $i\in W$ and $j\in U$

and

I. **warn** that should be a **DAG** meaning there should not be any directed cycles after the identification of the connected undirected and bidirected components,

II. **warn** that should be loopless,

III. **require** that **vertices are nicely ordered**: all vertices in U come before vertices in W plus i -> j implies i<j.

Questions:
1.  Are those warning and requirements ok? Should all of them be warnings for gaussianRing mixedGraph but turned into requirements for MLE computations?
2. Bibliographic reference for this partition? I can only find it in our internal documents.
3. If they are requirements for MLE computations, can we say that our package computes the MLE for any "ordered" loopless mixed graph?

**Comment by roserhp** [comment]
This issue intends to bring together #154, #149, #121. I will close all of them.

**Comment by roserhp** [comment]
Hi guys! It would be really helpful if you can check the intro in the documentation of GraphicalModelsMLE with
help GraphicalModelsMLE or helpView

**Comment by olgakuznetsova** [comment]
Hi!
I like it. A couple of small suggestions:

1. when you say mixedGraph, let's may be say either mixed graph, or MixedGraph, or graph of class @TO MixedGraph@ (the latter is what is recommended in the package writing style guide)
2. would it be possible to add sub-heading (just as bold short lines of text) and perhaps move the references towards the end with an appropriate subheading. Now it's a little hard to scan the text for relevant information.
3. perhaps add a description of the very first example as well?

**Comment by roserhp** [comment]
StatGraphs:
- add partitionLMG documentation from intro in GraphicalModelsMLE

GraphicalModels:
- extend documentation (gaussianRing, MixedGraph) with link to partitionLMG
- related methods (bidirectedEdgesMatrix, etc) 
- review introduction and be more clear about what kind of graphs can be used in each function

GraphicalModelsMLE:
- remove partition info in the intro

**Comment by roserhp** [comment]
Most of it is done, only missing step:
review introduction and be more clear about what kind of graphs can be used in each function

**Comment by olgakuznetsova** [comment]
Closing: the missing to-do is the same as issue #177
