### ISSUE TITLE
gaussianRing attributes

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#173]
@roserhp 

1. I noticed that the attribute R.graph is not documented or exported anywhere. M2 isn't complaining but shouldn't we document it somehow? what do you think is a good way?
2. Should we change the timing of saving R.graphType? Now it happens at the very end, i.e., after everything is converted to a MixedGraph. Wouldn't it be better to do it in the very beginning, so we preserve the original graph type. o/w it looks funny for the user.

**Comment by roserhp** [comment]
1. I would say R.graph can be kept local. Maybe this means it should be added as a local variable at the beginning?
2. I should reread the code...I'm not completely sure right now

**Comment by roserhp** [comment]
2. My only concern was gaussianVanishingIdeal. The way code is written we should keep it as it is now. I can tell you exactly why during the call.

**Comment by olgakuznetsova** [comment]
Update documentation accordingly

**Comment by roserhp** [comment]
Done, will be pushed tonight
