### ISSUE TITLE
gaussianParametrization: confusing reference to mixed graphs

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#187]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/ffb2fb754e94c6083883b2c9a7c2703e6cb61b84/AlgebraicStatistics/MLE/GraphicalModels.m2#L968-L990

@roserhp I wonder whether the current set-up (or the error messages at least) can be confusing to the user. We say that this function only works for gaussian rings of mixed graphs whereas in reality, it will also accept a gaussian ring of a digraph or a Bigraph (this is of course because on the backend, 
gaussianRing Digraph = gaussianRing mixedGraph Digraph
but this is not transparent to the user.
What do you think?
Related to issue #173

**Comment by roserhp** [comment]
You're right. Changed
