### ISSUE TITLE
Create separate documentation entries for types of input in gaussianRing

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#203]
(gaussianRing, Graph)
(gaussianRing, MixedGraph), etc

**Comment by roserhp** [comment]
This is done, can you guys check how it looks (I can't do helpView...)?

From the documentation of gaussianRing you should be able to access the documentation of each specific input type and it should be clear to the user.

**Comment by olgakuznetsova** [comment]
OMG, this is soo much better! Thank you!!
