### ISSUE TITLE
trekSeparation does not accept undirected edges

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#39]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/ce09cb54adc189cd0461cc7321a27ed601cc766a/AlgebraicStatistics/MLE/GraphicalModels.m2#L986-L1052

**Comment by harshitmotwani2015** [comment]
I will look into it.

**Comment by olgakuznetsova** [comment]
@harshitmotwani2015 can this be closed now?

**Comment by roserhp** [comment]
Considered in #97.
