### ISSUE TITLE
trekIdeal does not accept undirected edges

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#40]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/ce09cb54adc189cd0461cc7321a27ed601cc766a/AlgebraicStatistics/MLE/GraphicalModels.m2#L1053-L1090

**Comment by harshitmotwani2015** [comment]
I will look into it.

**Comment by olgakuznetsova** [comment]
@harshitmotwani2015 can this be closed now?

**Comment by harshitmotwani2015** [comment]
@olgakuznetsova 
I have not yet worked on it. 
Since it is a part of another project I think we will update this function when we upload the code of that project in the repository. I need to confirm it with @lukeamendola before doing anything for this function.

**Comment by roserhp** [comment]
Considered in #97.
