### ISSUE TITLE
Naming conflict after copying functions from Graphs

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#46]
Since we have 
`PackageExports => {"Graphs"}`
in the preamble of StatGraphs, then the functions defined in Graphs have their precedence. (And we cannot not export or import Graphs because we actually need it inside StatGraphs)

Dan suggested the following workaround: "use the standard synonym for exported symbols: StatGraphs$topologicalSort.
Use that everywhere instead of topologicalSort. This will confuse your users, too, since there will be two packages present that define the same symbol, in different ways. But at least they will get a message about shadowing and advice about synonyms."

I tried that and it works. See https://github.com/Macaulay2/Workshop-2020-Warwick/commit/e88c7619ddaeecf093e4ea5af0af688bc85738eb

But that basically means we need to add StatGraphs$ to every line of our code, which doesn't seem practical.

So, I suggest to actually have our own internal version of Graphs where we remove the conflicting functions.
@Macaulay2/graphicalmodelsmle what do you think?

**Comment by harshitmotwani2015** [comment]
I think it's better to have a totally independent internal version of Graphs (which we call StatsGraph) for our purpose and export this in GraphicalModels and GraphicalModelsMLE.

**Comment by olgakuznetsova** [comment]
Could you explain you mean by "totally independent"? How does this compare to what we agreed on in issue#38?

**Comment by harshitmotwani2015** [comment]
I mean a package which doesn't import Graphs

**Comment by olgakuznetsova** [comment]
Hm, I suggest to wait until others respond in that case. I'm not entirely
convinced that we should copy 5k lines of code to work on 100 of them.
IMHO, would be easier to have "our" Graphs where we remove everything
that's mentioned in Issue #38




to 20. elok. 2020 klo 14.00 harshitmotwani2015 (notifications@github.com)
kirjoitti:

**Comment by harshitmotwani2015** [comment]
Yes, I agree.

**Comment by harshitmotwani2015** [comment]
@olgakuznetsova I think this commit is fine and you can make a pull request to AlgebraicStatistics branch.

**Comment by olgakuznetsova** [comment]
closed in c8502dccac41cc00df2f59a19a6abf2ea91fcc0a
