### ISSUE TITLE
Packages dependent on Graphs

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#47]
Obtained by searching the M2 GitHub repo:

- ReactionNetworks
- Visualize
- BinomialEdgeIdeals
- GraphicalModels
- Chordal
-  SimplicialPosets
- PhylogeneticTrees
- Matroids
- NautyGraphs
- Posets - checked, doesn't call any of the functions from https://github.com/Macaulay2/Workshop-2020-Warwick/issues/38#issuecomment-670169947

**Comment by olgakuznetsova** [comment]
Ok, I realised that it's easier to just check when https://github.com/Macaulay2/Workshop-2020-Warwick/issues/38#issuecomment-670169947 appear in the M2 GitHub repo and the answer is only in "Graphs" and "GraphicalModels"

**Comment by roserhp** [comment]
Install and check for the packages listed by Olga work more or less fine. 

Exceptions:
- ReactionNetworks
- BinomialEdgeIdeals
- PhylogeneticTrees
- Posets

It seems all issues appear when executing external program 4ti2: rays, markov or groebner. Anyone has this program installed and can try?

**Comment by lukeamendola** [comment]
I uninstalled and then installed the latest version of "Graphs", then installed and checked these four packages. 

They all work fine! I don't get any errors.

**Comment by roserhp** [comment]
Do we need to keep this open if the only problem is #132, and it's still open?

**Comment by olgakuznetsova** [comment]
I reopened it because we'll need to move topSort and topologicalSort back to Graphs. This shouldn't be a problem for us but on the safe side, let's keep it open for now

**Comment by harshitmotwani2015** [comment]
I have checked all the above packages and all of them (except NautyGraphs) installed without errors with the current version of Graphs.

Can anyone check if they can install NautyGraphs? 

@olgakuznetsova @roserhp @luisgarciapuente @lukeamendola

**Comment by luisgarciapuente** [comment]
I check both Nauty and NautyGraphs and they both passed. It was not working but I looked at the M2 google group and I learned that  I had to install some GNU utilities (gsort). After I did that it worked w/o issues.
