### ISSUE TITLE
Add a function to confirm proper vertex ordering in LMG

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#64]

**Comment by roserhp** [comment]
In progress. It needs to be checked whether this is enough:

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/7a4e8bc28005f54634fbc962a68c025136116b3e/AlgebraicStatistics/MLE/GraphicalModels.m2#L637

**Comment by olgakuznetsova** [comment]
Would it make sense to make this a function in StatGraphs that we reuse elsewhere?

We define MixedGraphs in StatGraphs

**Comment by roserhp** [comment]
I thought it was better to leave mixedGraphs as general as possible...maybe at some point later on someone else wants to do something with mixedGraphs that does not require this ordering. I thought that, if we have time, we could do another function that orders the vertices in a way that is suitable for forming the partition. We can discuss this on Friday!

**Comment by olgakuznetsova** [comment]
I meant this could be a separate function that is not inside any other function and can be called by the users in the most generic setting (like isCyclic in Graphs)

**Comment by roserhp** [comment]
Ahh! Sure, that makes sense. Sorry I didn't read your comment properly...

**Comment by olgakuznetsova** [comment]
Hi @roserhp, 
do you think we can close this?

**Comment by roserhp** [comment]
Sure
