### ISSUE TITLE
Input as matrix instead of list

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#7]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/0819e39ec591e156cba4fcd9ec09904e7504a67d/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L89

Consider allowing input as matrix instead of a list of column matrices.

**Comment by harshitmotwani2015** [comment]
I have made changes to the file to care for both lists and matrices.
