### ISSUE TITLE
changeRing vs removeSvar

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#71]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/751a355fa5e8a8006087d392c3bd67c47d8a66ff/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L112-L121

@roserhp did you create the function removeSvar? could you check whether we still need it?

**Comment by roserhp** [comment]
This function was created by Harshit to use it in genListMatrix because he had some issues but I realized now why changeRing was not working for him. Works fine with changeRing now. So I removed both removeSvar and matRtolpR in GraphicalModelsMLE. Still only in my branch.

**Comment by roserhp** [comment]
ChangeRing removed as well
