### ISSUE TITLE
Finalize and clean up gensListmatrix

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#73]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/751a355fa5e8a8006087d392c3bd67c47d8a66ff/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L129-L155

We need to
- make this work for MixedGraphs
- decide whether to use removeSvar or changeRing

(see also issue #71)

**Comment by roserhp** [comment]
I've changed gensListmatrix into a function that does the substitution for whichever matrix we give to it:

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/c57d57c85f6914f9e87c6a53eb6189965f764789/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L107

This means that we need to retrieve Sinv from scoreEquations:
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/c57d57c85f6914f9e87c6a53eb6189965f764789/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L250

I've tried with this example and it seems to work fine:
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/c57d57c85f6914f9e87c6a53eb6189965f764789/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L775

This is only in my branch so far!
