### ISSUE TITLE
Remove scoreEquationsFromCovarianceMatrixUndir before release

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#75]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/751a355fa5e8a8006087d392c3bd67c47d8a66ff/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L268-L290

**Comment by olgakuznetsova** [comment]
or if we keep it, then add the same options as in the general case (saturation, input covariance matrix, etc)

**Comment by roserhp** [comment]
scoreEquationsFromCovarianceMatrix now calls scoreEquationsFromCovarianceMatrixUndir when the mixedGraph only has undirected edges. All options have been added everywhere
