### ISSUE TITLE
allow list of lists

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#76]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/80d62a740b874744e1699548ee492f05ed0015ea/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L160

 and

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/80d62a740b874744e1699548ee492f05ed0015ea/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L251

**Comment by roserhp** [comment]
Done. Only push to AlgebraicStatistics remains to be done.
