### ISSUE TITLE
Check if R is a GaussianRing

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#86]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1e778403e35581e1b86e5d50fc08a97d6313f91c/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L161

1. R is a GaussianRing 
2. if R is a GaussianRing of Undir, and if yes, the switch to Method for Undir
2. if R is a GaussianRing but not of a MixedGraph, give an error

**Comment by roserhp** [comment]
Done
