### ISSUE TITLE
Check compatibility of GaussianRing and Data, and Graph and Data

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#87]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1e778403e35581e1b86e5d50fc08a97d6313f91c/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L161

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1e778403e35581e1b86e5d50fc08a97d6313f91c/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L306

**Comment by roserhp** [comment]
Done.
