### ISSUE TITLE
Rename method to scoreEquations instead of scoreEquationsFromCovarianceMatrix

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#89]
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/1e778403e35581e1b86e5d50fc08a97d6313f91c/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L160

**Comment by roserhp** [comment]
Done
