### ISSUE TITLE
Issues and questions about gaussianRing and its matrices

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#94]
Hi @roserhp, 

could you help understand the following?

1. gaussianRing?bigraph doesn't seem to work 
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/686475dc1b7d06ccbbd65c1601715931aa963ddc/AlgebraicStatistics/MLE/LMGtests.m2#L431-L436

2. similarly, I can't get R.?gaussianRingData to work if the input is a Digraph, Digraph or MixedGraph

3. in directed/bidirectedEdgeMatrix we seem to allow only MixedGraphs. What about Digraphs and Bigraphs?
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/686475dc1b7d06ccbbd65c1601715931aa963ddc/AlgebraicStatistics/MLE/GraphicalModels.m2#L737-L777

4. I wanted to move SInv calculation to GraphicalModels but realised there is some method called cavarianceMatrix. Do you know whether it is relevant for us/should be kept in the future?
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/686475dc1b7d06ccbbd65c1601715931aa963ddc/AlgebraicStatistics/MLE/GraphicalModels.m2#L819-L854

5. What about gaussianMatrices?
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/686475dc1b7d06ccbbd65c1601715931aa963ddc/AlgebraicStatistics/MLE/GraphicalModels.m2#L854-L890

Thank you!

**Comment by olgakuznetsova** [comment]
Just in case, I need this for the the following code:
https://github.com/Macaulay2/Workshop-2020-Warwick/blob/170c25a2cdd87aaa3db8f05413257ee433f36e6d/AlgebraicStatistics/MLE/GraphicalModelsMLE.m2#L296-L302

**Comment by roserhp** [comment]
Addressed in #98
