### ISSUE TITLE
Digraph in markovMatrices

### ISSUE THREAD

**Issue by olgakuznetsova** [Macaulay2/Workshop-2020-Warwick#99]
@luisgarciapuente @lukeamendola  What are the Digraphs these comments are referring to? They don't seem to appear in the code. Should they be deleted?

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/ffb2fb754e94c6083883b2c9a7c2703e6cb61b84/AlgebraicStatistics/MLE/GraphicalModels.m2#L785

https://github.com/Macaulay2/Workshop-2020-Warwick/blob/ffb2fb754e94c6083883b2c9a7c2703e6cb61b84/AlgebraicStatistics/MLE/GraphicalModels.m2#L801

**Comment by luisgarciapuente** [comment]
I guess it was an comment left from a previous version of the function. It can be deleted for sure.

**Comment by olgakuznetsova** [comment]
I see, thanks!
